# Generated by Django 4.0.2 on 2022-02-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cagnote_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_hour",
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("academician", "payment_date", "reason"), name="payment_unique"
            ),
        ),
    ]
