# Generated by Django 4.0.2 on 2022-02-12 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cagnote_app', '0002_alter_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academician',
            options={'ordering': ['-overall_payment'], 'verbose_name': 'Academicien', 'verbose_name_plural': 'Academiciens'},
        ),
        migrations.AddField(
            model_name='academician',
            name='overall_payment',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='paiement total'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='academician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cagnote_app.academician'),
        ),
    ]
