# Generated by Django 4.0.2 on 2022-02-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cagnote_app', '0003_alter_academician_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academician',
            name='overall_payment',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='paiement total'),
        ),
    ]
